import { expect, test } from '@playwright/test'

test('homepage globe concept supports country selection and mobile layout', async ({ page }) => {
  const webglErrors: string[] = []
  page.on('console', (message) => {
    if (/INVALID_OPERATION|no buffer is bound/i.test(message.text())) webglErrors.push(message.text())
  })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.route('**/api/v1/**', (route) => route.fulfill({ json: { items: [] } }))
  await page.route('**/api/v1/users/me', (route) => route.fulfill({ status: 401, json: {} }))
  await page.goto('/')
  const section = page.getByRole('region', { name: 'A world of readers' })
  await section.scrollIntoViewIfNeeded()
  await expect(section.getByText('Concept preview · Fictional data')).toBeVisible()
  await expect(section.getByRole('button', { name: 'Rotate globe right' })).toBeEnabled()
  await expect(section.getByRole('button', { name: /disabled by reduced-motion/ })).toBeDisabled()
  const canvas = section.locator('canvas')
  const beforeDrag = await canvas.screenshot()
  const bounds = (await canvas.boundingBox())!
  await page.mouse.move(bounds.x + bounds.width / 2, bounds.y + bounds.height / 2)
  await page.mouse.down()
  await page.mouse.move(bounds.x + bounds.width / 2 + 90, bounds.y + bounds.height / 2 + 25, { steps: 8 })
  await page.mouse.up()
  expect((await canvas.screenshot()).equals(beforeDrag)).toBe(false)
  await section.getByRole('button', { name: /Brazil/ }).click()
  await expect(section.getByText('72,300,000')).toBeVisible()
  const label = section.locator('[class*="markerTooltip"]')
  await expect(label).toHaveText('Brazil')
  await expect(label).toBeVisible()
  await section.getByRole('button', { name: 'Rotate globe right' }).click()
  const viewport = page.viewportSize()!
  await page.setViewportSize({ ...viewport, width: viewport.width - 40 })
  await section.getByRole('button', { name: /France/ }).click()
  await expect(label).toHaveText('France')
  await expect(label).toBeVisible()
  await page.setViewportSize(viewport)
  await section.getByRole('button', { name: 'Rotate globe left' }).click()
  expect(await section.evaluate((element) => element.scrollWidth <= window.innerWidth)).toBe(true)
  await section.screenshot({ path: `test-results/market-globe-${test.info().project.name}.png` })
  expect(webglErrors).toEqual([])
})

test('automatic rotation can be paused and resumed', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.route('**/api/v1/**', (route) => route.fulfill({ json: { items: [] } }))
  await page.route('**/api/v1/users/me', (route) => route.fulfill({ status: 401, json: {} }))
  await page.goto('/')
  const section = page.getByRole('region', { name: 'A world of readers' })
  await section.scrollIntoViewIfNeeded()
  await section.getByRole('button', { name: 'Pause automatic rotation' }).click()
  const canvas = section.locator('canvas')
  const stopped = await canvas.screenshot()
  expect((await canvas.screenshot()).equals(stopped)).toBe(true)
  await section.getByRole('button', { name: 'Resume automatic rotation' }).click()
  await expect.poll(async () => (await canvas.screenshot()).equals(stopped)).toBe(false)
})
